version: "3"
services:

  database:
    container_name: database
    image: postgres:14
    env_file:
      - '.env'
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
        - -U
        - admin
    networks:
      - postgres

  backend:
    container_name: backend
    image: kikikita/parimate_bot:latest
    environment:
      PG_NAME: ${POSTGRES_DB}
      PG_USER: ${POSTGRES_USER}
      PG_PASSWORD: ${POSTGRES_PASSWORD}
      PG_HOST: database
      PG_PORT: 5432
      TOKEN: ${TOKEN}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - postgres

volumes:
  postgres:

networks:
  postgres:
    driver: bridge
